version: '3.8'

services:
  purchase-api:
    build: .
    container_name: purchase-analysis-api
    ports:
      - "10000:10000"              # снаружи и внутри контейнера 10000
    environment:
      - OLLAMA_HOST=ollama_android  # без http://
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=qwen2.5vl:32b
    networks:
      - ollama-1c
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  ollama-1c:
    external: true
